#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost/vehicledatabase
#  application:
#    name: vh
spring:
  datasource:
    url: jdbc:h2:mem:vehicledb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    data:
      mongodb:
        uri: mongodb://localhost/vehicledatabase
    application:
      name: vh

  jpa:
    hibernate:
      ddl-auto: update  # creates schema automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082

jwt:
  secret: mysupersecretkey123456789mytokenkey
  expiration: 86400000  # 24 hours in ms


app:
  name: Vehicle Management Systems
  version: 1.0.0
  description: API for managing vehicle services V1
  maintainer:
    name: SST class B brilliant students
    email: support@sst.com
